In [4]:
import pandas as pd

alburyList = ['£1,498.93', '£1,748.74', '£1,998.56', '£2,248.39', '£2,748.03', '£3,247.67', '£3,747.31', '£4,496.77']
artingtonList = ['£1,475.92', '£1,721.90', '£1,967.89', '£2,213.88', '£2,705.85', '£3,197.82', '£3,689.80', '£4,427.75']
ashList = ['£1,502.21', '£1,752.57', '£2,002.95', '£2,253.32', '£2,754.06', '£3,254.79', '£3,755.53', '£4,506.63']
eastClandonList = ['£1,493.85', '£1,742.81', '£1,991.79', '£2,240.77', '£2,738.72', '£3,236.66', '£3,734.61', '£4,481.53']
westClandonList = ['£1,476.30', '£1,722.34', '£1,968.39', '£2,214.45', '£2,706.55', '£3,198.64', '£3,690.75', '£4,428.89']
comptonList = ['£1,489.17', '£1,737.36', '£1,985.56', '£2,233.76', '£2,730.15', '£3,226.54', '£3,722.93', '£4,467.51']
effinghamList = ['£1,517.47', '£1,770.37', '£2,023.28', '£2,276.20', '£2,782.02', '£3,287.84', '£3,793.66', '£4,552.39']
eastHorsleyList = ['£1,490.75', '£1,739.20', '£1,987.67', '£2,236.13', '£2,733.05', '£3,229.96', '£3,726.88', '£4,472.25']
westHorsleyList = ['£1,493.87', '£1,742.84', '£1,991.82', '£2,240.80', '£2,738.75', '£3,236.70', '£3,734.66', '£4,481.59']
normandyList = ['£1,527.81', '£1,782.43', '£2,037.07', '£2,291.71', '£2,800.98', '£3,310.24', '£3,819.51', '£4,583.41']
ockhamList = ['£1,491.50', '£1,740.08', '£1,988.66', '£2,237.25', '£2,734.42', '£3,231.58', '£3,728.75', '£4,474.49']
pirbrightList = ['£1,493.02', '£1,741.85', '£1,990.69', '£2,239.53', '£2,737.20', '£3,234.87', '£3,732.55', '£4,479.05']
puttenhamList = ['£1,483.23', '£1,730.43', '£1,977.64', '£2,224.85', '£2,719.26', '£3,213.67', '£3,708.08', '£4,449.69']
ripleyList = ['£1,518.56', '£1,771.65', '£2,024.74', '£2,277.84', '£2,784.03', '£3,290.21', '£3,796.40', '£4,555.67']
stMarthaList = ['£1,475.12', '£1,720.97', '£1,966.82', '£2,212.68', '£2,704.39', '£3,196.09', '£3,687.80', '£4,425.35']
sealeSandsList = ['£1,477.55', '£1,723.80', '£1,970.07', '£2,216.33', '£2,708.85', '£3,201.36', '£3,693.88', '£4,432.65']
sendList = ['£1,478.41', '£1,724.81', '£1,971.21', '£2,217.62', '£2,710.42', '£3,203.22', '£3,696.03', '£4,435.23']
shacklefordList = ['£1,481.37', '£1,728.26', '£1,975.16', '£2,222.06', '£2,715.85', '£3,209.64', '£3,703.43', '£4,444.11']
shalfordList = ['£1,493.45', '£1,742.35', '£1,991.27', '£2,240.18', '£2,738.00', '£3,235.81', '£3,733.63', '£4,480.35']
shereList = ['£1,512.09', '£1,764.10', '£2,016.12', '£2,268.14', '£2,772.17', '£3,276.20', '£3,780.23', '£4,536.27']
tonghamList = ['£1,480.03', '£1,726.69', '£1,973.36', '£2,220.04', '£2,713.38', '£3,206.72', '£3,700.06', '£4,440.07']
wanboroughList = ['£1,472.27', '£1,717.64', '£1,963.03', '£2,208.41', '£2,699.17', '£3,189.92', '£3,680.68', '£4,416.81']
wisleyList = ['£1,452.04', '£1,694.04', '£1,936.05', '£2,178.06', '£2,662.07', '£3,146.08', '£3,630.10', '£4,356.11']
worplesdonList = ['£1,507.82', '£1,759.12', '£2,010.42', '£2,261.73', '£2,764.34', '£3,266.94', '£3,769.55', '£4,523.45']
guildfordList = ['£1,452.04', '£1,694.04', '£1,936.05', '£2,178.06', '£2,662.07', '£3,146.08', '£3,630.10', '£4,356.11']

dfStack = [alburyList, artingtonList, ashList, eastClandonList, westClandonList, comptonList, effinghamList, eastHorsleyList, westHorsleyList, normandyList, ockhamList, pirbrightList, puttenhamList, ripleyList, stMarthaList, sealeSandsList, sendList, shacklefordList, shalfordList, shereList, tonghamList, wanboroughList, wisleyList, worplesdonList, guildfordList]

df = pd.DataFrame(dfStack)

df.columns = ['Band A', 'Band B', 'Band C', 'Band D', 'Band E', 'Band F', 'Band G', 'Band H']

df = df.rename(index={0: 'Albury', 1: 'Artington', 2: 'Ash', 3: 'East Clandon', 4: 'West Clandon', 5: 'Compton', 6: 'Effingham', 7: 'East Horsley', 8: 'West Horsley', 9: 'Normandy', 10: 'Ockham', 11: 'Pirbright', 12: 'Puttenham', 13: 'Ripley', 14: 'St.Martha', 15: 'Seale & Sands', 16: 'Send', 17: 'Shackleford', 18: 'Shalford', 19: 'Shere', 20: 'Tongham', 21: 'Wanborough', 22: 'Wisley', 23: 'Worplesdon', 24: 'Guildford Town'})

print(df)

                   Band A     Band B     Band C     Band D     Band E  \
Albury          £1,498.93  £1,748.74  £1,998.56  £2,248.39  £2,748.03
Artington       £1,475.92  £1,721.90  £1,967.89  £2,213.88  £2,705.85
Ash             £1,502.21  £1,752.57  £2,002.95  £2,253.32  £2,754.06
East Clandon    £1,493.85  £1,742.81  £1,991.79  £2,240.77  £2,738.72
West Clandon    £1,476.30  £1,722.34  £1,968.39  £2,214.45  £2,706.55
Compton         £1,489.17  £1,737.36  £1,985.56  £2,233.76  £2,730.15
Effingham       £1,517.47  £1,770.37  £2,023.28  £2,276.20  £2,782.02
East Horsley    £1,490.75  £1,739.20  £1,987.67  £2,236.13  £2,733.05
West Horsley    £1,493.87  £1,742.84  £1,991.82  £2,240.80  £2,738.75
Normandy        £1,527.81  £1,782.43  £2,037.07  £2,291.71  £2,800.98
Ockham          £1,491.50  £1,740.08  £1,988.66  £2,237.25  £2,734.42
Pirbright       £1,493.02  £1,741.85  £1,990.69  £2,239.53  £2,737.20
Puttenham       £1,483.23  £1,730.43  £1,977.64  £2,224.85  £2,719.26
Ripley          £1,518.56  £1,771.65  £2,024.74  £2,277.84  £2,784.03
St.Martha       £1,475.12  £1,720.97  £1,966.82  £2,212.68  £2,704.39
Seale & Sands   £1,477.55  £1,723.80  £1,970.07  £2,216.33  £2,708.85
Send            £1,478.41  £1,724.81  £1,971.21  £2,217.62  £2,710.42
Shackleford     £1,481.37  £1,728.26  £1,975.16  £2,222.06  £2,715.85
Shalford        £1,493.45  £1,742.35  £1,991.27  £2,240.18  £2,738.00
Shere           £1,512.09  £1,764.10  £2,016.12  £2,268.14  £2,772.17
Tongham         £1,480.03  £1,726.69  £1,973.36  £2,220.04  £2,713.38
Wanborough      £1,472.27  £1,717.64  £1,963.03  £2,208.41  £2,699.17
Wisley          £1,452.04  £1,694.04  £1,936.05  £2,178.06  £2,662.07
Worplesdon      £1,507.82  £1,759.12  £2,010.42  £2,261.73  £2,764.34
Guildford Town  £1,452.04  £1,694.04  £1,936.05  £2,178.06  £2,662.07

                   Band F     Band G     Band H
Albury          £3,247.67  £3,747.31  £4,496.77
Artington       £3,197.82  £3,689.80  £4,427.75
Ash             £3,254.79  £3,755.53  £4,506.63
East Clandon    £3,236.66  £3,734.61  £4,481.53
West Clandon    £3,198.64  £3,690.75  £4,428.89
Compton         £3,226.54  £3,722.93  £4,467.51
Effingham       £3,287.84  £3,793.66  £4,552.39
East Horsley    £3,229.96  £3,726.88  £4,472.25
West Horsley    £3,236.70  £3,734.66  £4,481.59
Normandy        £3,310.24  £3,819.51  £4,583.41
Ockham          £3,231.58  £3,728.75  £4,474.49
Pirbright       £3,234.87  £3,732.55  £4,479.05
Puttenham       £3,213.67  £3,708.08  £4,449.69
Ripley          £3,290.21  £3,796.40  £4,555.67
St.Martha       £3,196.09  £3,687.80  £4,425.35
Seale & Sands   £3,201.36  £3,693.88  £4,432.65
Send            £3,203.22  £3,696.03  £4,435.23
Shackleford     £3,209.64  £3,703.43  £4,444.11
Shalford        £3,235.81  £3,733.63  £4,480.35
Shere           £3,276.20  £3,780.23  £4,536.27
Tongham         £3,206.72  £3,700.06  £4,440.07
Wanborough      £3,189.92  £3,680.68  £4,416.81
Wisley          £3,146.08  £3,630.10  £4,356.11
Worplesdon      £3,266.94  £3,769.55  £4,523.45
Guildford Town  £3,146.08  £3,630.10  £4,356.11